resource "azurerm_static_web_app" "frontend" {
  name                = "${var.app_name}-frontend"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location

  # Free tier — no charge
  sku_tier = "Free"
  sku_size = "Free"

  tags = {
    project     = var.app_name
    environment = var.environment
  }
}

# The GitHub Actions workflow for SWA deployment is auto-generated by Azure.
# After apply, retrieve the deployment token and add it as a GitHub Actions secret:
#   terraform output -raw static_web_app_api_key
# Set as GitHub secret: AZURE_STATIC_WEB_APPS_API_TOKEN

output "static_web_app_api_key" {
  description = "Deployment API key for Azure Static Web Apps — add as GitHub Actions secret AZURE_STATIC_WEB_APPS_API_TOKEN"
  value       = azurerm_static_web_app.frontend.api_key
  sensitive   = true
}
