# Generated by Django 4.2.29 on 2026-04-02 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GoodGame", "0002_gamehub_tag_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(choices=[(-1, "Downvote"), (1, "Upvote")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="GoodGame.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="postvote",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_vote_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="postvote",
            constraint=models.CheckConstraint(
                check=models.Q(("value__in", [-1, 1])), name="post_vote_value_valid"
            ),
        ),
    ]
