# Generated by Django 4.2.30 on 2026-05-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodGame', '0013_post_is_pinned'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='developerfeedback',
            new_name='GoodGame_de_game_hu_16e1ba_idx',
            old_name='dev_fb_hub_created_idx',
        ),
    ]
