# Generated by Django 4.2.30 on 2026-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "GoodGame",
            "0014_rename_dev_fb_hub_created_idx_goodgame_de_game_hu_16e1ba_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="attachment_original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
